spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000

  kafka:
    consumer:
      group-id: auth-service-dev
    listener:
      missing-topics-fatal: false

mail:
  host: localhost
  port: 1025
  username: dummy
  password: dummy

logging:
  level:
    root: DEBUG
    com.tinka: DEBUG
