# auth-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # prod: verify schema; use migrations for changes
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000
      # ssl: true               # uncomment if your Redis requires TLS

  kafka:
    consumer:
      group-id: auth-service-prod
    listener:
      missing-topics-fatal: true  # prod: fail fast if a topic is missing/misnamed

  mail:
    host: smtp.mailgun.org
    port: 587
    username: no-reply@yourdomain.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.tinka.auth: INFO
