spring:
  main:
    web-application-type: reactive   # ensure reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"   # your frontend dev server
            allowedMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth
          uri: http://auth.default.svc.cluster.local:8001
          predicates:
            - Path=/api/auth/**

        - id: products
          uri: http://products.default.svc.cluster.local:8002
          predicates:
            - Path=/api/products/**

        - id: orders
          uri: http://orders.default.svc.cluster.local:8003
          predicates:
            - Path=/api/orders/**

        - id: payments
          uri: http://payments.default.svc.cluster.local:8004
          predicates:
            - Path=/api/payments/**

        - id: notification
          uri: http://notification.default.svc.cluster.local:8005
          predicates:
            - Path=/api/notification/**

        - id: reviews
          uri: http://reviews.default.svc.cluster.local:8006
          predicates:
            - Path=/api/reviews/**

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
