spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      group-id: notification-service-prod
    listener:
      missing-topics-fatal: true     # prod: fail fast if required topics missing

  mail:
    host: smtp.mailgun.org
    port: 587
    username: no-reply@yourdomain.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    # For providers that require TLS-only connections, add:
    # properties.mail.smtp.ssl.enable: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.tinka.notification: INFO
