# orders-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # dev only; use validate/migrations in prod
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      group-id: orders-service-dev   # dev-only consumer group
    listener:
      missing-topics-fatal: false    # safe for dev bring-up

logging:
  level:
    root: DEBUG
    com.tinka.orders: DEBUG
