# products-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update       # dev only; use validate/migrations in prod
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000

  kafka:
    consumer:
      group-id: products-service-dev
    listener:
      missing-topics-fatal: false    # dev: don't crash if topics not created yet

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

logging:
  level:
    root: DEBUG
    com.tinka.products: DEBUG
