# products-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000
      # ssl: true   # uncomment if your Redis requires TLS

  kafka:
    consumer:
      group-id: products-service-prod
    listener:
      missing-topics-fatal: true     # prod: fail fast if required topics missing

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.tinka.products: INFO
