apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: adan762/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_NAME
              value: "application,gateway"
            - name: CONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: tinka-secret
                  key: CONFIG_USER
            - name: CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: tinka-secret
                  key: CONFIG_PASS
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            # --- Spring Cloud Config (URL + credentials) ---
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tinka-secret
                  key: CONFIG_USER
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tinka-secret
                  key: CONFIG_PASS
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
